name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - masters
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Setup Git Identity
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson -Dorg.gradle.jvmargs="-Xmx2048m"
          cp -f **/build/*.cs3 $GITHUB_WORKSPACE/builds/ 2>/dev/null || cp -f build/*.cs3 $GITHUB_WORKSPACE/builds/
          cp -f build/plugins.json $GITHUB_WORKSPACE/builds/

      - name: Push Compiled Extensions
        run: |
          cd $GITHUB_WORKSPACE/builds
          git add .
          # This command creates a commit only if there are changes to avoid exit code 1
          git diff-index --quiet HEAD || git commit -m "Build $GITHUB_SHA"
          git push origin builds